import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import SignUpLogin from "./components/SignUpLogin";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const merchant = session?.user;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f7f5fa]`}>
        <header className="w-full flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-white">
          <span className="text-2xl font-bold text-[#22223b] tracking-tight">PayTM</span>
          <div className="flex flex-col items-end text-right">
            {merchant ? (
              <>
                <span className="font-semibold text-[#6a51a6]">{merchant.name}</span>
                <span className="text-xs text-gray-500">{merchant.email}</span>
              </>
            ) : (
              <span className="text-xs text-gray-400">Not signed in</span>
            )}
          </div>
        </header>
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
